### ISSUE TITLE
Extra functionality

### ISSUE THREAD

**Issue by stasou** [PerfectlyNormal/tinymce-rails-imageupload#55]
I hacked around it and added functionality to also support other file types. In case it's image, it adds the image, otherwise it adds a link to the upload.

The hack consists in:
a. adding an extra json variable (isimage) which is 'true' if file type match(/image/).
b.if isimage=='true' as is else, create an \<a> tag instead of a \<img>
c.change the icon for the toolbar and some mesages

It is a very well formed plugin, thanks for having written it.

**Comment by sobrinho** [comment]
Thanks! Feel free to open a pull request if this is still relevant to you.
