### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by PerfectlyNormal** [PerfectlyNormal/tinymce-rails-imageupload#65]
As most who look at this project probably can see, I haven't been paying too much attention to it lately. I hardly use TinyMCE anywhere anymore, so fixing bugs and improving things aren't something I can dedicate a lot of time to.

If anyone are interested in taking over and maintaining the project, let me know.

**Comment by sobrinho** [comment]
I would be happy to take care of it! :)

**Comment by PerfectlyNormal** [comment]
Hi.

Sorry it's taken forever to respond, but things have been a bit crazy the last few days. I've added you as a collaborator, which I think should make it possible for you to fix things. If not, let me know, and I'll look into it.

**Comment by sobrinho** [comment]
Great, thanks! I will do some work on it :)
