### ISSUE TITLE
Set Content-Type to application/json in response

### ISSUE THREAD

**Issue by aaronchi** [PerfectlyNormal/tinymce-rails-imageupload#7]
I noticed that the plugin doesn't work if you actually return a json response. It seems to only work if you send a text/html response with json in it. I assume this is due to the way that the response is being parsed in the javascript.

Great start on a simple upload plugin though. Would be great to extend it and include a list view as well with a configurable endpoint for pulling in the image details. 

Thanks!

**Comment by Looooong** [comment]
can we append format to the link? Like `/tinymce_assets.json`

**Comment by PerfectlyNormal** [comment]
@Looooong might be possible to do and get a sensible response. Have you tried it?

The url the plugin uses can be customized. I don’t remember the exact parameter name, but it’s listed in the readme
