### ISSUE TITLE
Carrierwave usage

### ISSUE THREAD

**Issue by dannyvassallo** [PerfectlyNormal/tinymce-rails-imageupload#76]
@PerfectlyNormal I'm not sure if you want to add this to the docs somewhere as most of the examples seem to implement paperclip, but linked is a gist to a working carrierwave setup. May be useful to other developers.

https://gist.github.com/dannyvassallo/f0fff53bfd88114ec4e7

**Comment by dannyvassallo** [comment]
@PerfectlyNormal also just to note -- this works w/ rails 5  + ruby 2.3

**Comment by sobrinho** [comment]
Feel free to create a wiki page about that! :)
