### ISSUE TITLE
Compiling with tinymce-rails config.tinymce.install = :copy breaks.

### ISSUE THREAD

**Issue by Preen** [PerfectlyNormal/tinymce-rails-imageupload#82]
I had to change this line inside` lib/tasks/tinymce-uploadimage-asset.rake`
`assets = Pathname.new(File.expand_path(File.dirname(__FILE__) + "/../../vendor/assets/javascripts/tinymce"))`
To. 
`assets = Pathname.new(File.expand_path(File.dirname(__FILE__) + "/../../app/assets/javascripts/tinymce"))`

Otherwise I would get an "unknown file type" error

**Comment by botimer** [comment]
This fix is covered in pull request #88.

**Comment by PerfectlyNormal** [comment]
Thanks!
Try with v4.0.17.beta.3, which should fix it
