### ISSUE TITLE
Conflict with chrome extensions

### ISSUE THREAD

**Issue by Dmitriy-ateo** [PerfectlyNormal/tinymce-rails-imageupload#92]
First of all, thanks for your plugin it saves a lot of time.
But, recently our clients started complaining about some weird issue "Got a bad response from the server". 
The reason of this issue is a conflict with chrome plugins. Some of them add extra code to the page, and when you try to get response here: 
https://github.com/PerfectlyNormal/tinymce-rails-imageupload/blob/34a105e77f1746913b8989ad67b75c6f9bc4e8c8/app/assets/javascripts/tinymce/plugins/uploadimage/plugin.js#L131

it receives something like 

`<div id="some_plugins_extra_div_with_display_none"></div>{image:{url:"etc"}}`

Is there any chance to strip all html tags before you parse json response?

**Comment by PerfectlyNormal** [comment]
Hi

Thanks for your patience. I'm not super quick to respond any longer, unfortunately.

That sounds like an incredibly shitty Chrome plugin. Ultimately, I don't think we should do anything to work around it in this library. It expects JSON, and we don't want to start second-guessing or adding extra bloat trying to detect if it contains HTML and strip it.

The ideal thing would be to get #7 fixed, then the plugin should probably not insert anything extra.
I don't really use the library any more, so I have difficulties testing and implementing things, but if you want to take a stab at getting #7 fixed, I'd merge it in instead.
